#:import utils kivy.utils


<HomeScreen>:
    FloatLayout:
        GridLayout:
            canvas:
                Color:
                    rgb: utils.get_color_from_hex("#32a852")
                Rectangle:
                    size: self.size
                    pos: self.pos
            cols: 1
            pos_hint: {"top": 1, "left": 1}
            size_hint: 1, .1
            Label:
                # Home Label;
                text: "COVID-19 Status"
                id: top_label
        Carousel:
            loop : True
            pos_hint: {"top": .75, "left": 1}
            size_hint: 1, .5
            id: carousel_id

